# Esta configuración es por si no se encuentra la configuración del eureka-server en el servidor de
# configuración centralizada

#Configuration for failfast=false

server:
  port: ${EUREKA_SERVER_PORT:1111}

logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    cabanas.garcia.ismael: 'DEBUG'

spring:
  # Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
  thymeleaf:
    enabled: false     # Disable Thymeleaf

# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false