server:
  port: ${PORT:8888}

logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'INFO'
    cabanas.garcia.ismael: 'DEBUG'

spring:
  application:
    name: config-server  # Service registers under this name
  #profiles:
  #  active: ${SPRING_PROFILES_ACTIVE}
  #rabbitmq:
  #  host: docker.local
  #  port: 5672
  #  username: guest
  #  password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ismaelcabanas/config-repo
          basedir: target/config
---
spring:
  profiles: github
  cloud:
    config:
      server:
        git:
          uri: https://github.com/atSistemas/cygnus-config

---
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///D:/development/cygnus-config
          failOnError : false

---
spring:
  profiles: local-git
  cloud:
    config:
      server:
        git:
#         uri: file:///${HOME}/cygnus-config
         uri: file:///D:/development/cygnus-config